# Generated by Django 4.2.3 on 2026-10-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_paymentreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Added to the item price. Use 0 for no extra cost, negative to reduce.', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='taxrate',
            name='applies_after_discount',
            field=models.BooleanField(default=True, help_text='Calculate on the discounted subtotal instead of the full subtotal'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat amount added to the bill (used when type is Fixed Amount)', max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected when creating a new order'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='is_optional',
            field=models.BooleanField(default=True, help_text='Cashier may switch this tax off for an order'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers are applied/applied first'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from new orders (existing orders keep it)'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='name',
            field=models.CharField(help_text='e.g. VAT, WHT, Service Levy', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percent, e.g. 7.50 for 7.5% (used when type is Percentage)', max_digits=5),
        ),
        migrations.CreateModel(
            name='OrderTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='core.order')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_taxes', to='core.taxrate')),
            ],
            options={
                'verbose_name': 'Order Tax Line',
                'verbose_name_plural': 'Order Tax Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_modifiers', to='core.modifier')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='core.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Modifier',
                'verbose_name_plural': 'Order Item Modifiers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Size, Add-ons, Spice Level', max_length=100, unique=True)),
                ('min_select', models.PositiveIntegerField(default=0, help_text='How many the cashier must pick. 0 = optional')),
                ('max_select', models.PositiveIntegerField(default=1, help_text='Maximum allowed. 1 = single choice, higher = pick several')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('menu_items', models.ManyToManyField(blank=True, help_text='Menu items that offer this group. Leave empty to apply to every item.', related_name='modifier_groups', to='core.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='modifier',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.modifiergroup'),
        ),
        migrations.AlterUniqueTogether(
            name='modifier',
            unique_together={('group', 'name')},
        ),
    ]
