# Generated by Django 4.2.3 on 2026-10-03 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_taxes_and_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmovement',
            name='movement_type',
            field=models.CharField(choices=[('deposit', 'Deposit (Cash â†’ Bank)'), ('withdraw', 'Withdraw (Bank â†’ Cash)'), ('transfer', 'Transfer (Bank â†’ Bank)'), ('fee', 'Bank Fee (Out)'), ('interest', 'Interest (In)')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short name the cashier will recognise, e.g. "Table 5 - Rahim"', max_length=80)),
                ('items', models.JSONField(default=list, help_text='Snapshot of the cart lines')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_ids', models.JSONField(default=list, help_text='Taxes ticked when the bill was parked')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck once the held bill has been served')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_holds', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, help_text='Optional table this bill belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='core.table')),
            ],
            options={
                'verbose_name': 'Held Order',
                'verbose_name_plural': 'Held Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
