# Generated by Django 4.2.3 on 2026-10-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_bankmovement_movement_type_orderhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='core.unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=1, help_text='How many stock units are in one purchase unit (e.g. 1 bag = 25000 g).', max_digits=12),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_materials', to='core.unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='stock_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_materials', to='core.unit'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_unit',
            field=models.CharField(default='portion', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipesubrecipe',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
    ]
