# Generated by Django 4.2.3 on 2026-10-05 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_seed_units_backfill_stock_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_transactions', to='core.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='finished_reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Warn when ready portions fall to (or below) this level.', max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='finished_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ready-to-sell portions on hand (increased by production, decreased by sales).', max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_finished_stock',
            field=models.BooleanField(default=False, help_text='Produce this item in batches ahead of time and track ready portions.'),
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.DecimalField(decimal_places=2, help_text='Portions to produce.', max_digits=10)),
                ('produced_qty', models.DecimalField(decimal_places=2, default=0, help_text='Portions actually produced (filled on completion).', max_digits=10)),
                ('wastage_qty', models.DecimalField(decimal_places=2, default=0, help_text='Portions lost in production (recorded for reporting).', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='core.recipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productionrun'),
        ),
    ]
